### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Dewamade** [fadhiilrachman/line-py#10]
Hi, please help, now i cant login using link provided when start, before it is work, is it from Line that change something?

Traceback (most recent call last):
  File "E:/SHARE/scripts/line-py-master/singletrace.py", line 4, in <module>
    client = LineClient()
  File "E:\SHARE\scripts\line-py-master\linepy\client.py", line 24, in __init__
    self.qrLogin(keepLoggedIn=keepLoggedIn, systemName=systemName, appName=appName, showQr=showQr)
  File "E:\SHARE\scripts\line-py-master\linepy\api.py", line 121, in qrLogin
    self.tokenLogin(result.authToken, appName)
  File "E:\SHARE\scripts\line-py-master\linepy\api.py", line 133, in tokenLogin
    self.loadSession()
  File "E:\SHARE\scripts\line-py-master\linepy\api.py", line 30, in loadSession
    self.revision = self.poll.getLastOpRevision()
  File "build\bdist.win32\egg\akad\TalkService.py", line 3440, in getLastOpRevision
  File "build\bdist.win32\egg\akad\TalkService.py", line 3463, in recv_getLastOpRevision
akad.ttypes.TalkException: TalkException(parameterMap=None, reason=u'LOG_OUT', code=8)

**Comment by fadhiilrachman** [comment]
We will have an update with a fix for this very soon..

**Comment by anysz** [comment]
Ah i c

**Comment by angrust** [comment]
Apa sekarang sudah bisa digunakan?

**Comment by fadhiilrachman** [comment]
Yes, we have updated to 1.9.0
Please update your linepy with command
`pip install linepy --upgrade`

**Comment by Dewamade** [comment]
Superb mantap

**Comment by DiniAlfiaPertiwi** [comment]
I'm sorry. Why akad module is very much different? and why nothing videoProfile in Contact module.

**Comment by fadhiilrachman** [comment]
@DiniAlfiaPertiwi we have add that args, update now the akad package with this:
`pip install akad --upgrade`
