### ISSUE TITLE
Login success but get error akad.ttypes.SquareException

### ISSUE THREAD

**Issue by hoge6** [fadhiilrachman/line-py#21]
I got this error, when I try to login with email and password.
How can i fix this?

( I'm using Python 3.6.2 and linepy 3.0.6. )

code
```python
from linepy import *
line = LINE('EMAIL', 'PASSWORD')
line.log("Auth Token : " + str(line.authToken))
```

error
```
[2018-01-15 11:28:21.247885] [xxx] : Login success
Traceback (most recent call last):
  File "line2.py", line 12, in <module>
    line = LINE('EMAIL', "PASSWORD")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linepy/client.py", line 22, in __init__
    self.__initAll()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linepy/client.py", line 35, in __initAll
    self.squares    = self.getJoinedSquares()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linepy/square.py", line 7, in checkLogin
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linepy/square.py", line 266, in getJoinedSquares
    return self.square.getJoinedSquares(rq)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/akad/SquareService.py", line 1833, in getJoinedSquares
    return self.recv_getJoinedSquares()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/akad/SquareService.py", line 1857, in recv_getJoinedSquares
    raise result.e
akad.ttypes.SquareException: SquareException(errorCode=403, errorExtraInfo=None, reason='対応していないか不正なURLです。')
```

**Comment by fadhiilrachman** [comment]
I will try for fixing..

**Comment by kaoru-nishida** [comment]
This is a problem by line(naver)'s service area
Line Square supports in india
But Your account is Japan Account
So You can't use Line Square Services
You can fix that by commentouts

Open client.py...


    def __initAll(self):

        self.profile    = self.talk.getProfile()
        self.groups     = self.talk.getGroupIdsJoined()

        Models.__init__(self)
        Talk.__init__(self)
        Square.__init__(self)
        Call.__init__(self)
        Timeline.__init__(self)

        self.squares    = self.getJoinedSquares()

commentout↓

    def __initAll(self):

        self.profile    = self.talk.getProfile()
        self.groups     = self.talk.getGroupIdsJoined()

        Models.__init__(self)
        Talk.__init__(self)
        #Square.__init__(self)
        Call.__init__(self)
        Timeline.__init__(self)

        #self.squares    = self.getJoinedSquares()

Of cause You shouldn't use functions for line square
For example, searchSquareMembers(),createSquare(),getJoinedSquares()

**Comment by fadhiilrachman** [comment]
This bug has been fixed
Please upgrade for get newest version of linepy
`pip install linepy --upgrade`

**Comment by xprojectind** [comment]
File "/usr/local/lib/python3.5/dist-packages/linepy/client.py", line 18, in __init__
    self.loginWithCredential(_id=idOrAuthToken, passwd=passwd, certificate=certificate, systemName=systemName, appName=appName, keepLoggedIn=keepLoggedIn)
  File "/usr/local/lib/python3.5/dist-packages/linepy/auth.py", line 104, in loginWithCredential
    result = self.auth.loginZ(lReq)
  File "/usr/local/lib/python3.5/dist-packages/akad/AuthService.py", line 237, in loginZ
    return self.recv_loginZ()
  File "/usr/local/lib/python3.5/dist-packages/akad/AuthService.py", line 261, in recv_loginZ
    raise result.e
akad.ttypes.TalkException: TalkException(code=4, reason='Authentication fault exceeded', parameterMap=None)

**Comment by Mintu009** [comment]
I am getting the bellow error pls help me get it resopved 

python3 cus.py
Traceback (most recent call last):
  File "/storage/emulated/0/Movies/fullsb/fullsb/cus.py", line 23, in <module>
    client = LINE("mintu009verma@gmail.com","xxxxxxxxxx")
  File "/storage/emulated/0/Movies/fullsb/fullsb/linepy/client.py", line 21, in __init__
    self.loginWithCredential(_id=idOrAuthToken, passwd=passwd, certificate=certificate, systemName=systemName, appName=appName, keepLoggedIn=keepLoggedIn)
  File "/storage/emulated/0/Movies/fullsb/fullsb/linepy/auth.py", line 76, in loginWithCredential
    rsaKey = self.tauth.getRSAKeyInfo(self.provider)
  File "/storage/emulated/0/Movies/fullsb/fullsb/akad/TalkService.py", line 5110, in getRSAKeyInfo
    return self.recv_getRSAKeyInfo()
  File "/storage/emulated/0/Movies/fullsb/fullsb/akad/TalkService.py", line 5122, in recv_getRSAKeyInfo
    (fname, mtype, rseqid) = iprot.readMessageBegin()
  File "/storage/emulated/0/Movies/fullsb/fullsb/thrift/protocol/TCompactProtocol.py", line 326, in readMessageBegin
    proto_id = self.__readUByte()
  File "/storage/emulated/0/Movies/fullsb/fullsb/thrift/protocol/TCompactProtocol.py", line 305, in __readUByte
    result, = unpack('!B', self.trans.readAll(1))
  File "/storage/emulated/0/Movies/fullsb/fullsb/thrift/transport/TTransport.py", line 66, in readAll
    raise EOFError()
EOFError
~/.../fullsb/fullsb $
