### ISSUE TITLE
fix pls

### ISSUE THREAD

**Issue by ervan0707** [fadhiilrachman/line-py#3]
>>> from linepy import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "linepy\__init__.py", line 1, in <module>
    from .client import LineClient
  File "linepy\client.py", line 4, in <module>
    from .models import LineModels
  File "linepy\models.py", line 2, in <module>
    from .channel import LineChannel
  File "linepy\channel.py", line 2, in <module>
    from .client import LineClient
ImportError: cannot import name LineClient
![image](https://user-images.githubusercontent.com/32308373/32928918-3cbd4692-cb87-11e7-83d9-dd4528f5b36c.png)

**Comment by fadhiilrachman** [comment]
I have fixed this error, please update the lib:

` pip install linepy --linepy ` 

Thank you
