### ISSUE TITLE
Error login;revoke

### ISSUE THREAD

**Issue by RioBithub** [fadhiilrachman/line-py#35]
Input this PIN code '0002' on your LINE for smartphone in 2 minutes
[2018-02-08 19:46:33.156521] [mønö] : Login success
[2018-02-08 19:46:44.130510] Your LINE account is not support Square
Traceback (most recent call last):
  File "e.py", line 4, in <module>
    line = LINE('****@gmail.com', '*****)
  File "/data/data/com.termux/files/home/line-py/line-py/line-py/linepy/client.py", line 22, in __init__
    self.__initAll()
  File "/data/data/com.termux/files/home/line-py/line-py/line-py/linepy/client.py", line 33, in __initAll
    Timeline.__init__(self)
  File "/data/data/com.termux/files/home/line-py/line-py/line-py/linepy/timeline.py", line 18, in __init__
    Channel.__init__(self, self.channel, self.server.CHANNEL_ID['LINE_TIMELINE'], False)
  File "/data/data/com.termux/files/home/line-py/line-py/line-py/linepy/channel.py", line 20, in __init__
    self.__loginChannel()
  File "/data/data/com.termux/files/home/line-py/line-py/line-py/linepy/channel.py", line 27, in __loginChannel
    self.channelResult  = self.approveChannelAndIssueChannelToken(self.channelId)
  File "/data/data/com.termux/files/home/line-py/line-py/line-py/linepy/channel.py", line 6, in checkLogin
    return func(*args, **kwargs)
  File "/data/data/com.termux/files/home/line-py/line-py/line-py/linepy/channel.py", line 41, in approveChannelAndIssueChannelToken
    return self.client.approveChannelAndIssueChannelToken(channelId)
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/akad/ChannelService.py", line 243, in approveChannelAndIssueChannelToken
    return self.recv_approveChannelAndIssueChannelToken()
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/akad/ChannelService.py", line 267, in recv_approveChannelAndIssueChannelToken
    raise result.e
akad.ttypes.ChannelException: ChannelException(code=3, reason='REVOKE', parameterMap=None)

What i have to do ?

**Comment by HelloTan** [comment]
Waiting to 24 hours_^
