### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

### ISSUE THREAD

**Issue by mrsakau** [fadhiilrachman/line-py#43]
I have a problem like this, please help me :(

Traceback (most recent call last):
  File "echobot.py", line 4, in <module>
    line = LINE('**My Email**', '**My Password**')
  File "/usr/local/lib/python3.5/site-packages/linepy/client.py", line 18, in __init__
    self.loginWithCredential(_id=idOrAuthToken, passwd=passwd, certificate=certificate, systemName=systemName, appName=appName, keepLoggedIn=keepLoggedIn)
  File "/usr/local/lib/python3.5/site-packages/linepy/auth.py", line 73, in loginWithCredential
    rsaKey = self.tauth.getRSAKeyInfo(self.provider)
  File "/usr/local/lib/python3.5/site-packages/akad/TalkService.py", line 5109, in getRSAKeyInfo
    self.send_getRSAKeyInfo(provider)
  File "/usr/local/lib/python3.5/site-packages/akad/TalkService.py", line 5118, in send_getRSAKeyInfo
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.5/site-packages/thrift/transport/THttpClient.py", line 141, in _f
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/thrift/transport/THttpClient.py", line 181, in flush
    self.__http.endheaders()
  File "/usr/local/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/local/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

**Comment by hinqta** [comment]
me,too

**Comment by Alvin222** [comment]
Your ip is blocked by line maybs

**Comment by moepoi** [comment]
Change your IP because your ip already got banned
