### ISSUE TITLE
linepy

### ISSUE THREAD

**Issue by nuclear7171** [fadhiilrachman/line-py#65]
File "/home/adembugra89/burak/linepy/client.py", line 18, in __init__
    self.loginWithCredential(_id=idOrAuthToken, passwd=passwd, certificate=certificate, systemName=systemName, appName=appName, keepLoggedIn=keepLoggedIn)
  File "/home/adembugra89/burak/linepy/auth.py", line 104, in loginWithCredential
    result = self.auth.loginZ(lReq)
  File "/home/adembugra89/burak/akad/AuthService.py", line 237, in loginZ
    return self.recv_loginZ()
  File "/home/adembugra89/burak/akad/AuthService.py", line 261, in recv_loginZ
    raise result.e
akad.ttypes.TalkException: TalkException(code=4, reason='Authentication fault exceeded', parameterMap=None)

**Comment by nuclear7171** [comment]
Help

**Comment by lintangtimur** [comment]
post your code here

**Comment by nuclear7171** [comment]
Asia-northeast1-b I don't have linepy installed python3 bot pip3 install was made to upgrade the safety results this

**Comment by nuclear7171** [comment]
Python3 nadyasb.py

**Comment by nuclear7171** [comment]
root@instance-2:/home/adembugra89/burak# python3 z.py
Traceback (most recent call last):
  File "z.py", line 11, in <module>
    cl = LINE("******@hotmail.com", "******")
  File "/home/adembugra89/burak/linepy/client.py", line 18, in __init__
    self.loginWithCredential(_id=idOrAuthToken, passwd=passwd, certificate=certificate, systemName=systemName, appName=appName, keepLoggedIn=keepLoggedIn)
  File "/home/adembugra89/burak/linepy/auth.py", line 104, in loginWithCredential
    result = self.auth.loginZ(lReq)
  File "/home/adembugra89/burak/akad/AuthService.py", line 237, in loginZ
    return self.recv_loginZ()
  File "/home/adembugra89/burak/akad/AuthService.py", line 261, in recv_loginZ
    raise result.e
akad.ttypes.TalkException: TalkException(code=4, parameterMap=None, reason='Authentication fault exceeded')

**Comment by nuclear7171** [comment]
asia notheart

**Comment by Zulkiflimok** [comment]
self.qrLogin(keepLoggedIn=keepLoggedIn, systemName=systemName, appName=appName, showQr=showQr)
