### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by Noxturnix** [fadhiilrachman/line-py#8]
Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "linepy/client.py", line 24, in __init__
        self.qrLogin(keepLoggedIn=keepLoggedIn, systemName=systemName, appName=appName, showQr=showQr)
      File "linepy/api.py", line 121, in qrLogin
        self.tokenLogin(result.authToken, appName)
      File "linepy/api.py", line 133, in tokenLogin
        self.loadSession()
      File "linepy/api.py", line 30, in loadSession
        self.revision = self.poll.getLastOpRevision()
      File "/usr/local/lib/python2.7/dist-packages/akad/TalkService.py", line 3440, in getLastOpRevision
        return self.recv_getLastOpRevision()
      File "/usr/local/lib/python2.7/dist-packages/akad/TalkService.py", line 3451, in recv_getLastOpRevision
        (fname, mtype, rseqid) = iprot.readMessageBegin()
      File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TCompactProtocol.py", line 323, in readMessageBegin
        proto_id = self.__readUByte()
      File "/usr/local/lib/python2.7/dist-packages/thrift/protocol/TCompactProtocol.py", line 302, in __readUByte
        result, = unpack('!B', self.trans.readAll(1))
      File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TTransport.py", line 65, in readAll
        raise EOFError()
    EOFError

Today LINE server got updated. I use this module for my project and now I cannot login or update my work. Please help

**Comment by phettest02** [comment]
ปัญหาอาจอยู่ในบรรทัดนี้ที่คุณกำหนดหมายเลขอ้างอิงของไฟล์ให้selffpไม่self.fp:selffp=file("detailing.dat","rb")หากเป็นข้อผิดพลาดและรหัสของคุณจะเปิดไฟล์ไปself.fpจริงคุณอาจต้องการตรวจสอบว่าไฟล์ดังกล่าวมีเนื้อหาอยู่จริงหรือไม่ตัวอย่างเช่นข้อผิดพลาดแสดงว่าไฟล์ว่างเปล่าแก้ไข: ในความคิดเห็นของคำตอบนี้ S. Lott มีข้อสรุปที่ดีว่าสาเหตุข้อผิดพลาดที่ทำให้เกิดข้อผิดพลาดที่คุณเห็นว่าฉันกำลังวางที่นี่เพื่อความสมบูรณ์ของคำตอบ: "selffp จะเป็นไฟล์ที่เปิดไม่ได้และ self.fp (ไฟล์เก่าที่ถูกปิด) จะถูกใช้สำหรับการโหลด....เม้นมั่ว!!😁😁
[By.เพชร ทีมทดลองบอท]

**Comment by Dosugamea** [comment]
@Noxturnix 
It was fixed in version 1.8.5.
We need to update authToken with it.

@fadhiilrachman 
I appreciate your swift action.
Thank you!

**Comment by Noxturnix** [comment]
Ok, It's working now. Thanks all!
